import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Image from 'next/image';
import Link from 'next/link';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout( { children }: Readonly<{ children: React.ReactNode }> ) {
  console.log( 'server header, footer layout' )
  return (
    <html lang="en">
    <body className={ `${ geistSans.variable } ${ geistMono.variable } antialiased min-h-screen w-full` }>
      <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8  gap-16  font-[family-name:var(--font-geist-sans)]">
        <header>
          <Link href="/">Home</Link>
        </header>
        <div className='flex grow'>
          { children }
        </div>
        <footer className="row-start-3 flex gap-6 flex-wrap items-center justify-center">
          <Image
            aria-hidden
            src="/file.svg"
            alt="File icon"
            width={ 16 }
            height={ 16 }
          />
          <Image
            aria-hidden
            src="/window.svg"
            alt="Window icon"
            width={ 16 }
            height={ 16 }
          />
          <Image
            aria-hidden
            src="/globe.svg"
            alt="Globe icon"
            width={ 16 }
            height={ 16 }
          />
        </footer>
      </div>
    </body>
    </html>
);
}
